PROMPTS = [
    "berapa harga btc sekarang?",
    "harga bitcoin hari ini berapa?",
    "btc lagi naik atau turun?",
    "update harga bitcoin terbaru dong",
    "berapa nilai 1 btc ke usd?",
    "btc ke idr sekarang berapa?",
    "ethereum hari ini berapa harganya?",
    "harga eth terbaru berapa?",
    "eth lagi bullish atau bearish?",
    "update crypto market hari ini",
    "coin apa yang lagi naik hari ini?",
    "top gainers crypto hari ini apa aja?",
    "btc prediction hari ini gimana?",
    "prediksi harga bitcoin besok",
    "btc minggu ini bakal naik?",
    "market crypto lagi merah atau hijau?",
    "altcoin apa yang potensial sekarang?",
    "harga solana sekarang berapa?",
    "sol lagi bagus gak?",
    "update harga bnb hari ini",
    "bnb ke usd sekarang berapa?",
    "dogecoin hari ini berapa?",
    "doge lagi hype gak?",
    "harga xrp terbaru",
    "xrp ada potensi naik?",
    "btc dominance sekarang berapa?",
    "market cap crypto global berapa?",
    "volume trading btc hari ini berapa?",
    "fear and greed index sekarang berapa?",
    "btc support dan resistance dimana?",
    "analisa teknikal btc dong",
    "btc lagi overbought atau oversold?",
    "eth gas fee sekarang berapa?",
    "harga polygon matic hari ini",
    "matic lagi naik gak?",
    "ada coin baru yang bagus?",
    "rekomendasi crypto jangka pendek",
    "crypto bagus buat scalping apa?",
    "btc chart hari ini gimana?",
    "update candle btc sekarang",
    "btc timeframe 1h gimana?",
    "analisa btc 4h dong",
    "btc daily trend gimana?",
    "eth chart sekarang gimana?",
    "solana chart hari ini",
    "bnb trend hari ini gimana?",
    "ada news crypto terbaru?",
    "berita bitcoin hari ini apa?",
    "update regulasi crypto terbaru",
    "btc halving kapan?",
    "efek halving ke harga btc gimana?",
    "apa btc bakal all time high lagi?",
    "target harga btc tahun ini berapa?",
    "prediksi eth tahun ini",
    "altseason kapan mulai?",
    "apa sekarang altseason?",
    "portfolio crypto bagusnya apa?",
    "diversifikasi crypto gimana?",
    "risk management di crypto gimana?",
    "btc lagi sideways ya?",
    "kenapa btc turun hari ini?",
    "kenapa btc naik hari ini?",
    "apa faktor pengaruh harga btc?",
    "whale lagi akumulasi btc?",
    "on-chain data btc gimana?",
    "funding rate btc sekarang berapa?",
    "open interest btc berapa?",
    "liquidation btc hari ini berapa?",
    "support btc sekarang di berapa?",
    "resistance btc sekarang di berapa?",
    "trend crypto minggu ini gimana?",
    "coin apa yang undervalued?",
    "crypto apa yang overvalued?",
    "harga avax hari ini berapa?",
    "avax lagi bagus gak?",
    "harga link hari ini berapa?",
    "chainlink ada potensi naik?",
    "harga arb sekarang berapa?",
    "arbitrum lagi trend gak?",
    "optimism coin gimana?",
    "op lagi bullish?",
    "layer 2 mana yang bagus sekarang?",
    "nft market lagi gimana?",
    "defi masih worth it gak?",
    "staking crypto bagus dimana?",
    "apy staking eth berapa?",
    "yield farming masih jalan?",
    "harga usdt ke idr berapa?",
    "harga usdc ke idr berapa?",
    "stablecoin mana yang aman?",
    "btc vs gold mana lebih bagus?",
    "crypto vs saham mana lebih cuan?",
    "apa sekarang waktu yang tepat beli btc?",
    "strategi dca btc gimana?",
    "berapa minimal beli btc?",
    "exchange crypto yang bagus apa?",
    "wallet crypto yang aman apa?",
    "hardware wallet recommended apa?",
    "cara simpan crypto biar aman gimana?",
    "apa btc bisa 100k?",
    "apa eth bisa 10k?",
    "coin meme apa yang lagi naik?",
    "meme coin worth it gak?",
    "harga pepe coin berapa?",
    "crypto trending hari ini apa?",
    "top volume crypto hari ini apa?"
]
